version: "3.8"

networks:
  inception-network:
    driver: bridge
    name: inception-network

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/abel-hid/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/abel-hid/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception-network
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - inception-network
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/.
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    restart: always
    networks:
      - inception-network
