version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /$HOME/data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - /$HOME/data/wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - /$HOME/data/mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: always

networks:
  inception-network:
    name: inception-network
  
