CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'abel-hid'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'abel-hid'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';